name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Install dependencies using pnpm
        run: pnpm install --frozen-lockfile
      - name: Check Typescript using pnpm
        run: pnpm run lint
      - name: Build package using pnpm
        run: pnpm run build
      - name: Create release PR or publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run build
